const START_REQUEST = "START_REQUEST";
const RECEIVE_DATA = "RECEIVE_DATA";
const FINISH_REQUEST = "FINISH_REQUEST";

const ITEMS_PREFIX = "ITEMS";
export const ITEMS_START_REQUEST = ITEMS_PREFIX + START_REQUEST;
export const ITEMS_RECEIVE_DATA = ITEMS_PREFIX + RECEIVE_DATA;
export const ITEMS_FINISH_REQUEST = ITEMS_PREFIX + FINISH_REQUEST;

const BRANDS_PREFIX = "ITEMS";
export const BRANDS_START_REQUEST = BRANDS_PREFIX + START_REQUEST;
export const BRANDS_RECEIVE_DATA = BRANDS_PREFIX + RECEIVE_DATA;
export const BRANDS_FINISH_REQUEST = BRANDS_PREFIX + FINISH_REQUEST;
